Repository thornjad/jmthornton, pull requests merged in 2018-05, with the labels that each got.

#120 add fftf widget
  blog/index.html
  index.html
  tools/news/index.html
Labels: enhancement

#124 Post/clearnightretro
  blog/assets/images/20538585283_05b8f1a07d_o-e1480990838962.jpg
  blog/assets/images/20538585283_05b8f1a07d_o.jpg
  blog/assets/images/Google-Authenticator-150x150.jpg
  blog/assets/images/Google-Authenticator-300x169.jpg
  blog/assets/images/Google-Authenticator.jpg
  blog/assets/images/blue-compcard.jpg
  blog/assets/images/clj-preview.png
  blog/assets/images/code-background-cover.jpg
  blog/assets/images/code-fluff-asm.png
  blog/assets/images/computer-security-padlock.jpg
  blog/assets/images/cropped-icon-1-150x150.png
  blog/assets/images/cropped-icon-1-300x300.png
  blog/assets/images/cropped-icon-1-540x450.png
  blog/assets/images/cropped-icon-1-542x340.png
  blog/assets/images/cropped-icon-1-600x600.png
  blog/assets/images/cropped-icon-1-670x400.png
  blog/assets/images/cropped-icon-1.png
  blog/assets/images/cropped-icon-150x150.png
  blog/assets/images/cropped-icon-180x180.png
  blog/assets/images/cropped-icon-192x192.png
  blog/assets/images/cropped-icon-270x270.png
  blog/assets/images/cropped-icon-300x300.png
  blog/assets/images/cropped-icon-32x32.png
  blog/assets/images/cropped-icon.png
  blog/assets/images/cropped-laptop-coffeehouse.jpg
  blog/assets/images/ddg_thunderbird.png
  blog/assets/images/digital-lock.jpg
  blog/assets/images/groovy-preview.png
  blog/assets/images/icon-150x150.png
  blog/assets/images/icon-300x300.png
  blog/assets/images/keylaptop-150x150.jpg
  blog/assets/images/keylaptop-300x169.jpg
  blog/assets/images/linux.jpg
  blog/assets/images/preview-overlay.png
  blog/assets/images/preview-settings-view.png
  blog/assets/images/preview.png
  blog/assets/images/protonmail-logo.jpg
  blog/assets/images/retro-title.png
  blog/assets/images/scary-encryption-keys-tall.jpg
  blog/feed/jade.atom
  blog/index.html
  blog/p/clearnightretro.html
Labels: blog

#125 add pictures
  assets/images/jade-stpaul.jpg
  assets/images/jade-stpaul0.jpg
  assets/images/stephandjade.jpg
  index.html
Labels: enhancement

#126 switch to red alert
  blog/index.html
  blog/p/array-removeelement.html
  blog/p/clearnightretro.html
  blog/p/duplicated-ids.html
  blog/p/ecmascript2017.html
  blog/p/protonmail.html
  blog/p/switch-caps-esc.html
  blog/p/thunderbird-ddg.html
  blog/p/websitetimelapse.html
  blog/p/worm-of-1988.html
  blog/p/xmrstakcompile.html
  gallery/index.html
  index.html
  stephandjade.html
  tools/news/index.html
Labels: enhancement, important
